name: Secrets Update Test

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - name: Save Secret Before Sleep
        run: echo "${{ secrets.TEST_SECRET }}" > secret_before.txt

      - name: Wait for 1 minute
        run: sleep 60

      - name: Save Secret After Sleep
        run: echo "${{ secrets.TEST_SECRET }}" > secret_after.txt

      - name: Upload Secrets as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secret-values
          path: |
            secret_before.txt
            secret_after.txt
